export default {
  grid: {
    container: "100vw",
    containerContent: "86rem",
    gutter: "3.2rem",
  },
  media: {
    xxsmall: "380px",
    xsmall: "480px",
    small: "576px",
    medium: "767px",
    large: "992px",
    xlarge: "1200px",
  },
  border: {
    radius: "1.2rem",
  },
  colors: {
    bgGradient: {
      gradientSmall: "#00bf72",
      gradientLight: "#008793",
      gradientMedium: "#004d7a",
      gradientFull: "#051937",
    },
    mainLight: "#f8f8f8",
    mainDark: "#1e1e1e",
    textTitles: "#F4F66F",
    greenIcons: "#2eb01e",
  },
  font: {
    family: {
      Poppins: "'Poppins', sans-serif",
      Tangerine: "'Tangerine', cursive",
      GrechenFuemen: '"Grechen Fuemen", cursive',
      Roboto: '"Roboto", monospace',
    },
    sizes: {
      xsmall: "1.2rem",
      small: "1.4rem",
      medium: "1.6rem",
      large: "1.8rem",
      xlarge: "2.0rem",
      xxlarge: "2.4rem",
      biglarge: "2.8rem",
      xbiglarge: "3.2rem",
      xxbiglarge: "3.4rem",
      ultra: "5rem",
    },
    light: 300,
    normal: 500,
    bold: 700,
  },
  spacings: {
    xxsmall: "0.8rem",
    xsmall: "1.6rem",
    small: "2.4rem",
    medium: "3.2rem",
    large: "4.0rem",
    xlarge: "4.8rem",
    xxlarge: "5.6rem",
  },
} as const;
